"use strict";
import {supabase,getBarbers,getServices,getBookingSettings,getBarberDayReservations,saveCustomer,createReservation} from "./supabase.js";
const $=s=>document.querySelector(s);
const reserveForm=$("#reserveForm"),nextBtn=$("#nextBtn"),prevBtn=$("#prevBtn"),submitBtn=$("#submitBtn"),progressBar=$("#progressBar"),barbersContainer=$("#barbersContainer"),servicesContainer=$("#servicesContainer"),daysContainer=$("#daysContainer"),timesContainer=$("#timesContainer"),successModal=$("#successModal"),successDetails=$("#successDetails");
const steps=[1,2,3,4,5].map(n=>$(`#step${n}`));let currentStep=1;
const data={firstName:"",lastName:"",phone:"",barberId:"",barberName:"",serviceId:"",service:"",serviceDuration:30,date:"",displayDate:"",time:""};
let settings={opening_time:"10:00:00",closing_time:"22:00:00",slot_interval:30,booking_days_ahead:30},barbers=[],services=[],blocks=[];
const days=["یکشنبه","دوشنبه","سه‌شنبه","چهارشنبه","پنجشنبه","جمعه","شنبه"];
const digits=v=>String(v||"").replace(/[۰-۹]/g,d=>"۰۱۲۳۴۵۶۷۸۹".indexOf(d)).replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d));
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const faDate=d=>new Intl.DateTimeFormat("fa-IR-u-ca-persian",{year:"numeric",month:"long",day:"numeric"}).format(d);
const tm=v=>String(v||"").slice(0,5);const mins=t=>{const [h,m]=tm(t).split(":").map(Number);return h*60+m};const fmt=m=>`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`;
function showStep(n){currentStep=Math.max(1,Math.min(5,n));steps.forEach((s,i)=>s?.classList.toggle("active",i+1===currentStep));progressBar&&(progressBar.style.width=`${currentStep*20}%`);prevBtn&&(prevBtn.style.display=currentStep===1?"none":"flex");nextBtn&&(nextBtn.style.display=currentStep===5?"none":"flex");submitBtn&&(submitBtn.style.display=currentStep===5?"flex":"none");if(currentStep===4)createDays();if(currentStep===5)createTimes();window.scrollTo({top:0,behavior:"smooth"})}
function phoneSetup(){const p=$("#phone");p?.addEventListener("input",()=>p.value=digits(p.value).replace(/\D/g,"").slice(0,11))}
async function boot(){try{const [b,s,bs]=await Promise.all([getBarbers(),getServices(),getBookingSettings()]);barbers=(b||[]).filter(x=>x.active!==false);services=(s||[]).filter(x=>x.active!==false);settings={...settings,...(bs||{})};renderBarbers();renderServices()}catch(e){console.error(e);barbersContainer.innerHTML='<div class="time-message">خطا در دریافت اطلاعات. صفحه را دوباره بارگذاری کنید.</div>'}}
function renderBarbers(){barbersContainer.innerHTML=barbers.length?barbers.map(b=>`<label class="barber-card"><input type="radio" name="barber" value="${esc(b.id)}"><div class="barber-image"><img src="${esc(b.image_url||"images/barbers/default.jpg")}" alt="${esc(b.name)}"></div><div class="barber-info"><h4>${esc(b.name)}</h4><span>${esc(b.role||"آرایشگر")}</span></div></label>`).join(""):'<div class="time-message">آرایشگر فعالی برای رزرو وجود ندارد.</div>';barbersContainer.querySelectorAll("input").forEach(i=>i.addEventListener("change",()=>{const b=barbers.find(x=>x.id===i.value);data.barberId=b.id;data.barberName=b.name;data.date="";data.time="";createDays()}))}
function renderServices(){servicesContainer.innerHTML=services.length?services.map(s=>`<label class="service-card"><input type="radio" name="service" value="${esc(s.id)}"><div class="service-image"><img src="${esc(s.image_url||`images/services/${s.service_key||"default"}.jpg`)}" alt="${esc(s.name)}"></div><h4>${esc(s.name)}</h4><span class="service-duration">${Number(s.duration||30)} دقیقه</span></label>`).join(""):'<div class="time-message">خدمت فعالی برای رزرو وجود ندارد.</div>';servicesContainer.querySelectorAll("input").forEach(i=>i.addEventListener("change",()=>{const s=services.find(x=>x.id===i.value);data.serviceId=s.id;data.service=s.name;data.serviceDuration=Number(s.duration||30);data.time="";if(currentStep===5)createTimes()}))}
function blocksFor(date){return blocks.filter(b=>b.active&&b.block_date===date&&(!b.barber_id||b.barber_id===data.barberId))}
function dayClosed(date){return blocksFor(date).some(b=>!b.start_time&&!b.end_time)}
async function loadBlocks(date){const {data:d,error}=await supabase.from("availability_blocks").select("id,barber_id,block_date,start_time,end_time,block_type,title,reason,active").eq("active",true).eq("block_date",date);if(error)throw error;blocks=d||[]}
async async function createDays(){await loadAllDayBlocks();daysContainer.innerHTML="";const ahead=Number(settings.booking_days_ahead||30),today=new Date();for(let i=0;i<ahead;i++){const d=new Date(today);d.setDate(today.getDate()+i);const id=iso(d),closed=dayClosed(id),c=document.createElement("button");c.type="button";c.className=`day-card${data.date===id?" selected":""}${closed?" disabled":""}`;c.innerHTML=`<span class="day-name">${days[d.getDay()]}</span><span class="day-date">${faDate(d)}</span>${closed?'<small>بسته</small>':''}`;c.disabled=closed;c.addEventListener("click",()=>{data.date=id;data.displayDate=faDate(d);data.time="";createDays();if(currentStep===4)showStep(5)});daysContainer.appendChild(c)}}
async function loadAllDayBlocks(){const {data:d}=await supabase.from("availability_blocks").select("id,barber_id,block_date,start_time,end_time,block_type,title,reason,active").eq("active",true).gte("block_date",iso(new Date())).lte("block_date",(()=>{const x=new Date();x.setDate(x.getDate()+Number(settings.booking_days_ahead||30));return iso(x)})());blocks=d||[];if(false){}

async function createTimes(){timesContainer.innerHTML="";if(!data.barberId)return showTime("ابتدا آرایشگر را انتخاب کنید.");if(!data.serviceId)return showTime("ابتدا خدمت را انتخاب کنید.");if(!data.date)return showTime("ابتدا روز را انتخاب کنید.");timesContainer.innerHTML='<div class="time-loading">در حال بررسی ساعت‌های آزاد...</div>';try{await loadBlocks(data.date);const reservations=await getBarberDayReservations(data.barberId,data.date);const slots=generateSlots();let count=0;slots.forEach(time=>{const c=document.createElement("button");c.type="button";c.className="time-card";const blocked=isBlocked(time,reservations)||isBlockedByAvailability(time);const past=isPast(data.date,time);const close=mins(time)+Number(data.serviceDuration||30)>mins(tm(settings.closing_time));if(blocked||past||close){c.classList.add("booked");c.disabled=true;c.innerHTML=`<i class="fa-solid fa-lock"></i><span>${time}</span><small>${past?"گذشته":blocked?"بسته / رزرو شده":"خارج از ساعت کاری"}</small>`}else{count++;c.innerHTML=`<i class="fa-regular fa-clock"></i><span>${time}</span>`;if(data.time===time)c.classList.add("selected");c.addEventListener("click",()=>{timesContainer.querySelectorAll(".time-card:not(.booked)").forEach(x=>x.classList.remove("selected"));c.classList.add("selected");data.time=time})}timesContainer.appendChild(c)});if(!count)showTime("برای این روز ساعت آزادی وجود ندارد.")}catch(e){console.error(e);showTime("خطا در بررسی ساعت‌های رزرو.")}}
function generateSlots(){const start=mins(settings.opening_time||"10:00"),end=mins(settings.closing_time||"22:00"),step=Number(settings.slot_interval||30),out=[];for(let m=start;m<end;m+=step)out.push(fmt(m));return out}
function isBlocked(t,rows){const a=mins(t),z=a+Number(data.serviceDuration||30);return rows.some(r=>r.status==='reserved'&&a<mins(r.time||r.start_time)+Number(r.service_duration||30)&&z>mins(r.time||r.start_time))}
function isBlockedByAvailability(t){const a=mins(t),z=a+Number(data.serviceDuration||30);return blocksFor(data.date).some(b=>a<(b.end_time?mins(b.end_time):1440)&&z>(b.start_time?mins(b.start_time):0))}
function isPast(date,time){if(date!==iso(new Date()))return false;return mins(time)<=new Date().getHours()*60+new Date().getMinutes()}
function showTime(t){timesContainer.innerHTML=`<div class="time-message">${esc(t)}</div>`}
function validate(){if(currentStep===1){const f=$("#firstName").value.trim(),l=$("#lastName").value.trim(),p=digits($("#phone").value.trim());if(!f||!l)return alert("نام و نام خانوادگی را کامل کنید."),false;if(!/^09\d{9}$/.test(p))return alert("شماره موبایل معتبر وارد کنید."),false;data.firstName=f;data.lastName=l;data.phone=p;return true}if(currentStep===2&&!data.barberId)return alert("آرایشگر را انتخاب کنید."),false;if(currentStep===3&&!data.serviceId)return alert("خدمت را انتخاب کنید."),false;if(currentStep===4&&!data.date)return alert("روز را انتخاب کنید."),false;if(currentStep===5&&!data.time)return alert("ساعت را انتخاب کنید."),false;return true}
nextBtn?.addEventListener("click",()=>validate()&&showStep(currentStep+1));prevBtn?.addEventListener("click",()=>showStep(currentStep-1));reserveForm?.addEventListener("submit",async e=>{e.preventDefault();if(![1,2,3,4,5].every(()=>validate()))return;submitBtn.disabled=true;submitBtn.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> در حال ثبت رزرو...';try{await loadBlocks(data.date);const rows=await getBarberDayReservations(data.barberId,data.date);if(isBlocked(data.time,rows)||isBlockedByAvailability(data.time))throw Object.assign(new Error("این ساعت دیگر قابل رزرو نیست."),{code:"conflict"});const customerId=await saveCustomer({firstName:data.firstName,lastName:data.lastName,phone:data.phone,barberId:data.barberId,barberName:data.barberName,service:data.service,date:data.date});const reservationId=await createReservation({...data,customerId});showSuccess({...data},reservationId);reserveForm.dataset.submitted="true"}catch(e){console.error(e);alert(e.code==='conflict'?"این ساعت رزرو یا بسته شده است. لطفاً ساعت دیگری انتخاب کنید.":"خطا در ثبت رزرو. لطفاً دوباره تلاش کنید.");data.time="";showStep(5)}finally{if(!reserveForm.dataset.submitted){submitBtn.disabled=false;submitBtn.innerHTML='<i class="fa-solid fa-check"></i> ثبت رزرو'}}});
function showSuccess(d,id){successDetails.innerHTML=`<div><strong>نام:</strong> ${esc(d.firstName)} ${esc(d.lastName)}</div><div><strong>آرایشگر:</strong> ${esc(d.barberName)}</div><div><strong>خدمت:</strong> ${esc(d.service)}</div><div><strong>مدت:</strong> ${esc(d.serviceDuration)} دقیقه</div><div><strong>تاریخ:</strong> ${esc(d.displayDate)}</div><div><strong>ساعت:</strong> ${esc(d.time)}</div><div><strong>کد رزرو:</strong> ${esc(id)}</div>`;successModal.classList.add("active");document.body.style.overflow="hidden"}
document.addEventListener("DOMContentLoaded",async()=>{showStep(1);phoneSetup();await boot();createDays()});
